name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Execute Gradle build (including tests)
        run: ./gradlew build

  compileMinJosmVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Compile the JOSM plugin using min JOSM version (plugin.main.version)
        run: ./gradlew compileJava_minJosm
