name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  gradle-jobs:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Execute Gradle build (including tests)
            task: build
          - name: Compile the JOSM plugin using min JOSM version (plugin.main.version)
            task: compileJava_minJosm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle task
        run: ./gradlew ${{ matrix.task }}
